"""
predict.py - Inference module for single-image pneumonia prediction.

Designed to be imported by FastAPI (or any other caller).
All heavy state (model, transforms) is loaded ONCE at module/app startup
via the `PneumoniaPredictor` class, then reused for every request.

Usage (standalone):
    python predict.py path/to/image.jpg
    python predict.py path/to/image.jpg --threshold 0.4

Usage (programmatic):
    from predict import PneumoniaPredictor

    predictor = PneumoniaPredictor()          # loads model once
    result    = predictor.predict(image_path) # call for each image
"""

from __future__ import annotations

import argparse
import io
import time
from pathlib import Path
from typing import Union

import torch
import torch.nn as nn
from PIL import Image
from torchvision import transforms

from models import config
from models.model import load_checkpoint
from models.preprocess import build_val_transform


# ---------------------------------------------------------------------------
# Inference transform (delegates to preprocess.py)
# ---------------------------------------------------------------------------

def _build_inference_transform() -> transforms.Compose:
    """Return the deterministic preprocessing pipeline for a single image."""
    return build_val_transform()


# ---------------------------------------------------------------------------
# Predictor class
# ---------------------------------------------------------------------------

class PneumoniaPredictor:
    """
    Stateful predictor: loads the model once and holds it in memory.

    Parameters
    ----------
    model_path : path to the .pth checkpoint (defaults to inference_model.pth
                 generated by export_model_for_inference, falls back to
                 best_model.pth).
    device     : "cpu" (default) or "cuda".
    threshold  : probability threshold above which the sample is classified
                 as PNEUMONIA. Default 0.5.
    """

    def __init__(
        self,
        model_path: Union[str, Path, None] = None,
        device:     str                    = config.DEVICE,
        threshold:  float                  = 0.5,
    ):
        self.device    = device
        self.threshold = threshold
        self.transform = _build_inference_transform()

        # Resolve checkpoint path
        inference_path = config.CHECKPOINT_DIR / "inference_model.pth"
        if model_path is None:
            if inference_path.exists():
                model_path = inference_path
            else:
                model_path = config.BEST_MODEL_PATH

        self.model_path = Path(model_path)
        self.model      = self._load_model()

    # ------------------------------------------------------------------
    # Private helpers
    # ------------------------------------------------------------------

    def _load_model(self) -> nn.Module:
        """Load checkpoint and put model into eval mode on the target device."""
        if not self.model_path.exists():
            raise FileNotFoundError(
                f"Model checkpoint not found: {self.model_path}\n"
                "Run train.py first to generate a checkpoint."
            )

        model, _ = load_checkpoint(
            path=self.model_path,
            device=self.device,
        )
        model.eval()
        # Disable gradient computation globally for this model instance
        for param in model.parameters():
            param.requires_grad = False

        print(f"[PneumoniaPredictor] Model loaded from: {self.model_path}")
        print(f"[PneumoniaPredictor] Running on: {self.device}")
        return model

    def _preprocess(
        self,
        source: Union[str, Path, bytes, Image.Image],
    ) -> torch.Tensor:
        """
        Accept a file path, raw bytes, or a PIL Image and return
        a [1, 3, H, W] float tensor ready for the model.
        CXRPreprocess inside the transform handles CLAHE + denoise + resize.
        """
        if isinstance(source, Image.Image):
            img = source
        elif isinstance(source, (bytes, bytearray)):
            img = Image.open(io.BytesIO(source))
        else:
            img = Image.open(str(source))

        # transform pipeline: CXRPreprocess -> ToTensor -> Normalize
        tensor = self.transform(img)          # [3, H, W]
        return tensor.unsqueeze(0)            # [1, 3, H, W]

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    @torch.no_grad()
    def predict(
        self,
        source: Union[str, Path, bytes, Image.Image],
    ) -> dict:
        """
        Run inference on a single chest X-ray image.

        Parameters
        ----------
        source : file path (str/Path), raw image bytes, or PIL.Image.

        Returns
        -------
        dict with keys:
            label        : str   - "NORMAL" or "PNEUMONIA"
            label_index  : int   - 0 (NORMAL) or 1 (PNEUMONIA)
            probability  : float - P(PNEUMONIA), range [0, 1]
            confidence   : float - confidence in the predicted class [0, 1]
            threshold    : float - decision threshold used
            inference_ms : float - inference wall-clock time in milliseconds
        """
        t0 = time.perf_counter()

        tensor = self._preprocess(source).to(self.device)
        logit  = self.model(tensor)                      # [1, 1]
        prob   = torch.sigmoid(logit).item()             # scalar float

        inference_ms = (time.perf_counter() - t0) * 1000

        label_index = int(prob >= self.threshold)
        label       = config.CLASS_NAMES[label_index]
        confidence  = prob if label_index == 1 else 1.0 - prob

        return {
            "label":        label,
            "label_index":  label_index,
            "probability":  round(prob, 6),
            "confidence":   round(confidence, 6),
            "threshold":    self.threshold,
            "inference_ms": round(inference_ms, 2),
        }

    @torch.no_grad()
    def predict_batch(
        self,
        sources: list[Union[str, Path, bytes, Image.Image]],
    ) -> list[dict]:
        """
        Run inference on a list of images.
        More efficient than calling predict() in a loop because images
        are batched into a single forward pass.

        Returns a list of result dicts in the same order as `sources`.
        """
        t0 = time.perf_counter()

        tensors = torch.cat(
            [self._preprocess(s) for s in sources], dim=0
        ).to(self.device)                               # [N, 3, H, W]

        logits = self.model(tensors)                    # [N, 1]
        probs  = torch.sigmoid(logits).squeeze(1)       # [N]

        inference_ms = (time.perf_counter() - t0) * 1000
        per_image_ms = inference_ms / max(len(sources), 1)

        results = []
        for prob_val in probs.cpu().tolist():
            label_index = int(prob_val >= self.threshold)
            label       = config.CLASS_NAMES[label_index]
            confidence  = prob_val if label_index == 1 else 1.0 - prob_val
            results.append({
                "label":        label,
                "label_index":  label_index,
                "probability":  round(prob_val, 6),
                "confidence":   round(confidence, 6),
                "threshold":    self.threshold,
                "inference_ms": round(per_image_ms, 2),
            })

        return results


# ---------------------------------------------------------------------------
# Module-level singleton (imported by FastAPI at startup)
# ---------------------------------------------------------------------------
# The FastAPI app should do:
#
#   from predict import get_predictor
#   predictor = get_predictor()           # called once in lifespan/startup
#
# Or simply import the module-level instance directly:
#
#   from predict import predictor
#

_predictor_instance: PneumoniaPredictor | None = None


def get_predictor(
    model_path: Union[str, Path, None] = None,
    device:     str                    = config.DEVICE,
    threshold:  float                  = 0.5,
) -> PneumoniaPredictor:
    """
    Return the module-level singleton PneumoniaPredictor.
    Creates it on first call; subsequent calls return the cached instance.
    Thread-safe for read-only inference (GIL protects single-assignment).
    """
    global _predictor_instance
    if _predictor_instance is None:
        _predictor_instance = PneumoniaPredictor(
            model_path=model_path,
            device=device,
            threshold=threshold,
        )
    return _predictor_instance


# ---------------------------------------------------------------------------
# CLI entry point  (python predict.py image.jpg)
# ---------------------------------------------------------------------------

def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Pneumonia prediction on a single image")
    p.add_argument("image", type=str, help="Path to chest X-ray image")
    p.add_argument(
        "--checkpoint", type=str, default=None,
        help="Override checkpoint path",
    )
    p.add_argument(
        "--threshold", type=float, default=0.5,
        help="Decision threshold (default: 0.5)",
    )
    p.add_argument(
        "--device", type=str, default=config.DEVICE,
    )
    return p.parse_args()


if __name__ == "__main__":
    args = parse_args()

    predictor = PneumoniaPredictor(
        model_path=args.checkpoint,
        device=args.device,
        threshold=args.threshold,
    )

    result = predictor.predict(args.image)

    print("\n--- Prediction Result ---")
    for k, v in result.items():
        print(f"  {k:<15}: {v}")
